import type { StudioPreset, PopoverStudioState } from "../types";

export const DEFAULT_POPOVER_STATE: PopoverStudioState = {
  "triggerLabel": "Open insights",
  "title": "Workspace insight",
  "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
  "body": "Use this panel for short interactive content that does not need dialog-level modality.",
  "primaryAction": "Apply",
  "secondaryAction": "Cancel",
  "id": "workspace-popover",
  "triggerId": "workspace-popover-trigger",
  "contentId": "workspace-popover-content",
  "labelledBy": "workspace-popover-title",
  "describedBy": "workspace-popover-description",
  "openMode": "uncontrolled",
  "defaultOpen": true,
  "modal": false,
  "closeOnEscape": true,
  "closeOnInteractOutside": true,
  "closeOnScroll": false,
  "side": "bottom",
  "align": "center",
  "offset": 12,
  "collisionPadding": 16,
  "sameWidth": false,
  "sticky": "partial",
  "showArrow": true,
  "arrowSize": 12,
  "arrowShape": "triangle",
  "showOverlay": false,
  "overlayOpacity": 22,
  "width": 360,
  "maxHeight": 320,
  "padding": 20,
  "gap": 12,
  "radius": 20,
  "borderWidth": 1,
  "shadow": 38,
  "background": "#0f172a",
  "foreground": "#e5eefb",
  "muted": "#94a3b8",
  "accent": "#38bdf8",
  "border": "#334155",
  "fontFamily": "Inter",
  "titleSize": 18,
  "bodySize": 14,
  "fontWeight": 700,
  "animation": "scale-fade",
  "duration": 180,
  "reducedMotion": false,
  "previewState": "open"
};

export const POPOVER_PRESETS: StudioPreset[] = [
  {
    "id": "premium-glass-compact",
    "family": "premium",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "premium",
      "saas",
      "glass",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 330,
      "maxHeight": 320,
      "padding": 16,
      "gap": 8,
      "radius": 24,
      "borderWidth": 1,
      "shadow": 34,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "premium-glass-spacious",
    "family": "premium",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "premium",
      "saas",
      "glass",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 460,
      "maxHeight": 320,
      "padding": 28,
      "gap": 18,
      "radius": 24,
      "borderWidth": 1,
      "shadow": 34,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "premium-soft-compact",
    "family": "premium",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "premium",
      "editorial",
      "soft",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 330,
      "maxHeight": 320,
      "padding": 16,
      "gap": 8,
      "radius": 28,
      "borderWidth": 1,
      "shadow": 16,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "premium-soft-spacious",
    "family": "premium",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "premium",
      "editorial",
      "soft",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 460,
      "maxHeight": 320,
      "padding": 28,
      "gap": 18,
      "radius": 28,
      "borderWidth": 1,
      "shadow": 16,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "premium-crisp-compact",
    "family": "premium",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "premium",
      "admin",
      "crisp",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 330,
      "maxHeight": 320,
      "padding": 16,
      "gap": 8,
      "radius": 12,
      "borderWidth": 1,
      "shadow": 10,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "premium-crisp-spacious",
    "family": "premium",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "premium",
      "admin",
      "crisp",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 460,
      "maxHeight": 320,
      "padding": 28,
      "gap": 18,
      "radius": 12,
      "borderWidth": 1,
      "shadow": 10,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "premium-hero-compact",
    "family": "premium",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "premium",
      "commerce",
      "hero",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 330,
      "maxHeight": 320,
      "padding": 16,
      "gap": 8,
      "radius": 30,
      "borderWidth": 2,
      "shadow": 46,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "premium-hero-spacious",
    "family": "premium",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "premium",
      "commerce",
      "hero",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 460,
      "maxHeight": 320,
      "padding": 28,
      "gap": 18,
      "radius": 30,
      "borderWidth": 2,
      "shadow": 46,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "editorial-glass-compact",
    "family": "editorial",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "editorial",
      "saas",
      "glass",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 330,
      "maxHeight": 320,
      "padding": 16,
      "gap": 8,
      "radius": 24,
      "borderWidth": 1,
      "shadow": 34,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "editorial-glass-spacious",
    "family": "editorial",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "editorial",
      "saas",
      "glass",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 460,
      "maxHeight": 320,
      "padding": 28,
      "gap": 18,
      "radius": 24,
      "borderWidth": 1,
      "shadow": 34,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "editorial-soft-compact",
    "family": "editorial",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "editorial",
      "editorial",
      "soft",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 330,
      "maxHeight": 320,
      "padding": 16,
      "gap": 8,
      "radius": 28,
      "borderWidth": 1,
      "shadow": 16,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "editorial-soft-spacious",
    "family": "editorial",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "editorial",
      "editorial",
      "soft",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 460,
      "maxHeight": 320,
      "padding": 28,
      "gap": 18,
      "radius": 28,
      "borderWidth": 1,
      "shadow": 16,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "editorial-crisp-compact",
    "family": "editorial",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "editorial",
      "admin",
      "crisp",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 330,
      "maxHeight": 320,
      "padding": 16,
      "gap": 8,
      "radius": 12,
      "borderWidth": 1,
      "shadow": 10,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "editorial-crisp-spacious",
    "family": "editorial",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "editorial",
      "admin",
      "crisp",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 460,
      "maxHeight": 320,
      "padding": 28,
      "gap": 18,
      "radius": 12,
      "borderWidth": 1,
      "shadow": 10,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "editorial-hero-compact",
    "family": "editorial",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "editorial",
      "commerce",
      "hero",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 330,
      "maxHeight": 320,
      "padding": 16,
      "gap": 8,
      "radius": 30,
      "borderWidth": 2,
      "shadow": 46,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "editorial-hero-spacious",
    "family": "editorial",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "editorial",
      "commerce",
      "hero",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 460,
      "maxHeight": 320,
      "padding": 28,
      "gap": 18,
      "radius": 30,
      "borderWidth": 2,
      "shadow": 46,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "admin-glass-compact",
    "family": "admin",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "admin",
      "saas",
      "glass",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 330,
      "maxHeight": 320,
      "padding": 16,
      "gap": 8,
      "radius": 24,
      "borderWidth": 1,
      "shadow": 34,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "admin-glass-spacious",
    "family": "admin",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "admin",
      "saas",
      "glass",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 460,
      "maxHeight": 320,
      "padding": 28,
      "gap": 18,
      "radius": 24,
      "borderWidth": 1,
      "shadow": 34,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "admin-soft-compact",
    "family": "admin",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "admin",
      "editorial",
      "soft",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 330,
      "maxHeight": 320,
      "padding": 16,
      "gap": 8,
      "radius": 28,
      "borderWidth": 1,
      "shadow": 16,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "admin-soft-spacious",
    "family": "admin",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "admin",
      "editorial",
      "soft",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 460,
      "maxHeight": 320,
      "padding": 28,
      "gap": 18,
      "radius": 28,
      "borderWidth": 1,
      "shadow": 16,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "admin-crisp-compact",
    "family": "admin",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "admin",
      "admin",
      "crisp",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 330,
      "maxHeight": 320,
      "padding": 16,
      "gap": 8,
      "radius": 12,
      "borderWidth": 1,
      "shadow": 10,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "admin-crisp-spacious",
    "family": "admin",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "admin",
      "admin",
      "crisp",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 460,
      "maxHeight": 320,
      "padding": 28,
      "gap": 18,
      "radius": 12,
      "borderWidth": 1,
      "shadow": 10,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "admin-hero-compact",
    "family": "admin",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "admin",
      "commerce",
      "hero",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 330,
      "maxHeight": 320,
      "padding": 16,
      "gap": 8,
      "radius": 30,
      "borderWidth": 2,
      "shadow": 46,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "admin-hero-spacious",
    "family": "admin",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "admin",
      "commerce",
      "hero",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 460,
      "maxHeight": 320,
      "padding": 28,
      "gap": 18,
      "radius": 30,
      "borderWidth": 2,
      "shadow": 46,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "commerce-glass-compact",
    "family": "commerce",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "commerce",
      "saas",
      "glass",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 330,
      "maxHeight": 320,
      "padding": 16,
      "gap": 8,
      "radius": 24,
      "borderWidth": 1,
      "shadow": 34,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "commerce-glass-spacious",
    "family": "commerce",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "commerce",
      "saas",
      "glass",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 460,
      "maxHeight": 320,
      "padding": 28,
      "gap": 18,
      "radius": 24,
      "borderWidth": 1,
      "shadow": 34,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "commerce-soft-compact",
    "family": "commerce",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "commerce",
      "editorial",
      "soft",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 330,
      "maxHeight": 320,
      "padding": 16,
      "gap": 8,
      "radius": 28,
      "borderWidth": 1,
      "shadow": 16,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "commerce-soft-spacious",
    "family": "commerce",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "commerce",
      "editorial",
      "soft",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 460,
      "maxHeight": 320,
      "padding": 28,
      "gap": 18,
      "radius": 28,
      "borderWidth": 1,
      "shadow": 16,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "commerce-crisp-compact",
    "family": "commerce",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "commerce",
      "admin",
      "crisp",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 330,
      "maxHeight": 320,
      "padding": 16,
      "gap": 8,
      "radius": 12,
      "borderWidth": 1,
      "shadow": 10,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "commerce-crisp-spacious",
    "family": "commerce",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "commerce",
      "admin",
      "crisp",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 460,
      "maxHeight": 320,
      "padding": 28,
      "gap": 18,
      "radius": 12,
      "borderWidth": 1,
      "shadow": 10,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "commerce-hero-compact",
    "family": "commerce",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "commerce",
      "commerce",
      "hero",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 330,
      "maxHeight": 320,
      "padding": 16,
      "gap": 8,
      "radius": 30,
      "borderWidth": 2,
      "shadow": 46,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "commerce-hero-spacious",
    "family": "commerce",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "commerce",
      "commerce",
      "hero",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 460,
      "maxHeight": 320,
      "padding": 28,
      "gap": 18,
      "radius": 30,
      "borderWidth": 2,
      "shadow": 46,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "support-glass-compact",
    "family": "support",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "support",
      "saas",
      "glass",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 330,
      "maxHeight": 320,
      "padding": 16,
      "gap": 8,
      "radius": 24,
      "borderWidth": 1,
      "shadow": 34,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "support-glass-spacious",
    "family": "support",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "support",
      "saas",
      "glass",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 460,
      "maxHeight": 320,
      "padding": 28,
      "gap": 18,
      "radius": 24,
      "borderWidth": 1,
      "shadow": 34,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "support-soft-compact",
    "family": "support",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "support",
      "editorial",
      "soft",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 330,
      "maxHeight": 320,
      "padding": 16,
      "gap": 8,
      "radius": 28,
      "borderWidth": 1,
      "shadow": 16,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "support-soft-spacious",
    "family": "support",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "support",
      "editorial",
      "soft",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 460,
      "maxHeight": 320,
      "padding": 28,
      "gap": 18,
      "radius": 28,
      "borderWidth": 1,
      "shadow": 16,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "support-crisp-compact",
    "family": "support",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "support",
      "admin",
      "crisp",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 330,
      "maxHeight": 320,
      "padding": 16,
      "gap": 8,
      "radius": 12,
      "borderWidth": 1,
      "shadow": 10,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "support-crisp-spacious",
    "family": "support",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "support",
      "admin",
      "crisp",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 460,
      "maxHeight": 320,
      "padding": 28,
      "gap": 18,
      "radius": 12,
      "borderWidth": 1,
      "shadow": 10,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "support-hero-compact",
    "family": "support",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "support",
      "commerce",
      "hero",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 330,
      "maxHeight": 320,
      "padding": 16,
      "gap": 8,
      "radius": 30,
      "borderWidth": 2,
      "shadow": 46,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "support-hero-spacious",
    "family": "support",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "support",
      "commerce",
      "hero",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 460,
      "maxHeight": 320,
      "padding": 28,
      "gap": 18,
      "radius": 30,
      "borderWidth": 2,
      "shadow": 46,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "system-glass-compact",
    "family": "system",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "system",
      "saas",
      "glass",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 330,
      "maxHeight": 320,
      "padding": 16,
      "gap": 8,
      "radius": 24,
      "borderWidth": 1,
      "shadow": 34,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "system-glass-spacious",
    "family": "system",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "system",
      "saas",
      "glass",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 460,
      "maxHeight": 320,
      "padding": 28,
      "gap": 18,
      "radius": 24,
      "borderWidth": 1,
      "shadow": 34,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "system-soft-compact",
    "family": "system",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "system",
      "editorial",
      "soft",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 330,
      "maxHeight": 320,
      "padding": 16,
      "gap": 8,
      "radius": 28,
      "borderWidth": 1,
      "shadow": 16,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "system-soft-spacious",
    "family": "system",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "system",
      "editorial",
      "soft",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 460,
      "maxHeight": 320,
      "padding": 28,
      "gap": 18,
      "radius": 28,
      "borderWidth": 1,
      "shadow": 16,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "system-crisp-compact",
    "family": "system",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "system",
      "admin",
      "crisp",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 330,
      "maxHeight": 320,
      "padding": 16,
      "gap": 8,
      "radius": 12,
      "borderWidth": 1,
      "shadow": 10,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "system-crisp-spacious",
    "family": "system",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "system",
      "admin",
      "crisp",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 460,
      "maxHeight": 320,
      "padding": 28,
      "gap": 18,
      "radius": 12,
      "borderWidth": 1,
      "shadow": 10,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "system-hero-compact",
    "family": "system",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "system",
      "commerce",
      "hero",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 330,
      "maxHeight": 320,
      "padding": 16,
      "gap": 8,
      "radius": 30,
      "borderWidth": 2,
      "shadow": 46,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  },
  {
    "id": "system-hero-spacious",
    "family": "system",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "system",
      "commerce",
      "hero",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "triggerLabel": "Open insights",
      "title": "Workspace insight",
      "description": "Popover content with placement, arrow, dismissal, and focus behavior controls.",
      "body": "Use this panel for short interactive content that does not need dialog-level modality.",
      "primaryAction": "Apply",
      "secondaryAction": "Cancel",
      "id": "workspace-popover",
      "triggerId": "workspace-popover-trigger",
      "contentId": "workspace-popover-content",
      "labelledBy": "workspace-popover-title",
      "describedBy": "workspace-popover-description",
      "openMode": "uncontrolled",
      "defaultOpen": true,
      "modal": false,
      "closeOnEscape": true,
      "closeOnInteractOutside": true,
      "closeOnScroll": false,
      "side": "bottom",
      "align": "center",
      "offset": 12,
      "collisionPadding": 16,
      "sameWidth": false,
      "sticky": "partial",
      "showArrow": true,
      "arrowSize": 12,
      "arrowShape": "triangle",
      "showOverlay": false,
      "overlayOpacity": 22,
      "width": 460,
      "maxHeight": 320,
      "padding": 28,
      "gap": 18,
      "radius": 30,
      "borderWidth": 2,
      "shadow": 46,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "fontFamily": "Inter",
      "titleSize": 18,
      "bodySize": 14,
      "fontWeight": 700,
      "animation": "scale-fade",
      "duration": 180,
      "reducedMotion": false,
      "previewState": "open"
    }
  }
];
